format = "$directory$all"
command_timeout = 1000

[[kubernetes.contexts]]
context_pattern = "^aws.*prod.*"
style = "#ff000c"
context_alias = "aws-prod-eu-west-1"


[[kubernetes.contexts]]
context_pattern = "^aws.*qa.*"
style = "#ffff00"
context_alias = "aws-qa-eu-west-1"

[[kubernetes.contexts]]
context_pattern = "^aws.*dev.*"
style = "#64ff00"
context_alias = "aws-dev-eu-west-1"

[kubernetes]
disabled = false
format = '\([âˆ](bold fg:33)[$context]($style):[$namespace](bright-white)\) '
#format = '\([âˆ](bold fg:33)[$cluster](fg:166):[$namespace](dimmed green)\) '

[aws]
disabled = false
force_display = true
style = 'yellow'

[python]
disabled = true
python_binary = "python3"
detect_extensions = ["py", "ipynb"]
detect_files = [
  "pyproject.toml",
  "Pipfile",
  "requirements.txt",
  "poetry.lock",
  "setup.py",
  ".python-version",
]
detect_folders = [".venv", "venv"]

[battery]
disabled = false
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[lua]
disabled = true

[git_branch]
disabled = false
format = "on [$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "[++($count)](green)"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[package]
disabled = true
format = "is [$symbol$version]($style) "
symbol = "ğŸ“¦ "
style = "208 bold"

[helm]
disabled = true
format = "via [$symbol$version]($style) "
symbol = "âˆ "
style = "bold white"

[nodejs]
disabled = true
format = "via [$symbol($version )]($style)"
symbol = "ğŸ’  "
style = "bold green"

[terraform]
disabled = true

[cmd_duration]
disabled = false
min_time = 2_000
format = "took [$duration]($style) "
style = "bold yellow"

[hostname]
ssh_only = true
ssh_symbol = 'ğŸŒ '
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.payoneer.com'
disabled = false


[c]
disabled = true
# Don't exec cc/gcc/clang to fetch version
commands = [] # default is ["cc", "gcc", "clang", "zig cc"]
# And/or make it very hard to trigger:
detect_extensions = []
detect_files = []
detect_folders = []
